### ISSUE TITLE
添加一个 起名的功能

### ISSUE THREAD

**Issue by wangfeng-1** [dreamhunter2333/chatgpt-tarot-divination#15]
根据用户输入的生日、姓氏、性别或者想要的风格等来进行取名

**Comment by dreamhunter2333** [comment]
不错的主意

**Comment by dreamhunter2333** [comment]
已增加
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/32295532/233768595-29572af8-6cce-40a9-bc21-52757c8d86e9.png">
